apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-api-configmap
data:
  API_PORT: "8080"
  API_DB_FILEPATH: "/persist/db.json"
  CRAWLER_BASE_URL: http://synergychat-crawler.crawler.svc.cluster.local:8080

